### ISSUE TITLE
We already have a counsel-rg command

### ISSUE THREAD

**Issue by kaushalmodi** [julienXX/counsel-ripgrep#1]
Hi,

We already have a very good ripgrep support in `counsel.el`: [See here][1]

It would be nice if you can merge your improvements upstream in the `counsel.el` itself.

[1]: https://github.com/abo-abo/swiper/blob/80d3fe3f65bd4a73140511a3481acc06daa4b309/counsel.el#L1787-L1848

**Comment by julienXX** [comment]
Sorry @kaushalmodi I had not seen it. I'm deleting this repo then. Thanks for notifying me!
